name: CI
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build myapp and deploy to minikube
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@latest
      with:
        cache: false
        start-args: ''
    - name: Try the cluster !
      run: kubectl get pods -A
    - name: Build image
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        docker build -f ./Dockerfile -t myapp:latest .
        echo -n "verifying images:"
        docker images        
    - name: Run a container
      run: |
        eval $(minikube -p minikube docker-env)
        docker run -d --name=myapp -p 8080:8080 myapp:latest
        echo "--- checking containers ---"
        docker ps
    - name: Deploy to minikube
      run: |
        kubectl delete pods --all
        kubectl delete deployments --all
        kubectl delete services --all
        kubectl apply -f ./manifests/
    - name: Check the cluster
      run: |
        kubectl get po
        kubectl get deployments
        kubectl get services
        echo "--- get events info ---"
        kubectl get events
        echo "--- describing pods ----"
        kubectl describe pods
    - name: Run sercvice
      run: 
        minikube service myapp-service
