name: CI
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build myapp and deploy to minikube
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@latest
      with:
        cache: false
    - name: Try the cluster !
      run: kubectl get pods -A
    - name: Build image
      run: |
        export SHELL=/bin/bash
        eval $(minikube docker-env)
        docker build -f ./Dockerfile -t myapp:latest .
        echo -n "verifying images:"
        docker images        
        minikube image load myapp:latest
    - name: Deploy to minikube
      run: |
        kubectl apply -f ./manifests/
        kubectl wait --for=condition=ready pods --all
    - name: Check the cluster
      run: |
        kubectl get po
        kubectl get deployments
        kubectl get services
        echo "--- get events info ---"
        kubectl get events
        echo "--- describing pods ----"
        kubectl describe pods
    - name: Event log
      run:
        kubectl get events --all-namespaces  --sort-by='.metadata.creationTimestamp' --kubeconfig=/etc/kubernetes/admin.conf
    - name: Run sercvice
      run: |
        minikube service list
        minikube service myapp-service --url
        echo -n "------------------opening the service------------------"
        curl $(minikube service myapp-service --url)/version
    - name: get minikube logs
      run:
        minikube logs
